#!/usr/bin/env bash

set -e

rsync -av --ignore-existing /etc/nginx/assets/ /etc/nginx

rm -fr \
  /etc/nginx-vhosts \
;

mkdir -p \
  /etc/vhosts \
  /etc/nginx-vhosts \
;

unset \
  listen_address \
  nginx_user_array \
  nginx_user \
  ERROR_PREFIX \
  WARNING_PREFIX \
;

listen_address=${LISTEN_ADDRESS:-127.0.0.1}

cat <<EOF > /etc/dnsmasq.conf
listen-address=$listen_address
interface=eth0
EOF

ERROR_PREFIX="\e[31mERROR\e[0m"
WARNING_PREFIX="\e[91mWARNING\e[0m"

nginx_user_array=(`grep -q -o "^user\s\+[^;]\+" /etc/nginx/**/*.conf`)
[[ -n ${nginx_user_array[1]} ]] && nginx_user="${nginx_user_array[1]}" || nginx_user="nginx"

for d in $(find /etc/vhosts -type d -maxdepth 1 -mindepth 1); do

  unset \
    hostname \
    conf_dir \
    vhost_conf \
    ssl_directives \
  ;

  hostname="${d##*/}"
  conf_dir="$d/deploy/dev/nginx"
  vhost_conf="$conf_dir/vhost.conf"

  echo
  echo -e "[ \e[1;35m$hostname\e[0m ]"

  [[ -f $vhost_conf ]] || {
    echo -e "$WARNING_PREFIX: $vhost_conf missing, skipping setup..."
    continue
  }

  echo "address=/$hostname/$listen_address" >> /etc/dnsmasq.conf

  if [[ -f "$conf_dir/local/certificate.crt" ]]; then

    ssl_directives="
      ssl_certificate     $conf_dir/local/certificate.crt;
      ssl_certificate_key $conf_dir/local/certificate.key;
      listen              $listen_address:443 ssl;
    "

    if [[ $nginx_user != root ]]; then

      for f in \
        "$conf_dir/local/certificate.crt" \
        "$conf_dir/local/certificate.key"  \
      ; do

        su $nginx_user -s /bin/sh -c "cat $f > /dev/null" || {
          echo -e "$WARNING_PREFIX: make sure $f file exists and is readable by unprivileged users"
          echo -e "$ERROR_PREFIX: $f not readable by $nginx_user user"
        }

      done

    fi

  fi

  for e in \
    "server" \
    "listen" \
    "server_name" \
    "ssl_certificate" \
    "ssl_certificate_key" \
  ; do
    if grep -q "^[^#]\?$e\s\+" $vhost_conf; then
      echo -e "$WARNING_PREFIX: $e directive detected in $vhost_conf"
    fi
  done

  cat <<EOF > /etc/nginx-vhosts/$hostname.conf
server {
  $ssl_directives
  listen $listen_address:80;
  server_name $hostname;
  include $vhost_conf;
  include $conf_dir/local/*.conf;
}
EOF

  nginx -t || {
    echo -e "$ERROR_PREFIX: $vhost_conf validation failed [ $d ]"
  }

done

find /services -name run -exec chmod +x {} \;

echo -e "\n[ \e[32mStarting Services...\e[0m ]"

s6-svscan /services

